/** Seed past questions — expand over time. Shape mirrors CardStack mock. */

export type PastQuestion = {
  id: string
  subjectId: string
  year: number
  exam: 'JAMB' | 'WAEC' | 'NECO'
  question: string
  options: Record<'A' | 'B' | 'C' | 'D', string>
  answer: 'A' | 'B' | 'C' | 'D'
  explanation: string
}

export const PAST_QUESTIONS: PastQuestion[] = [
  {
    id: 'mth-001',
    subjectId: 'mathematics',
    year: 2023,
    exam: 'JAMB',
    question: 'If 2x + 5 = 17, what is the value of x?',
    options: { A: '4', B: '6', C: '8', D: '12' },
    answer: 'B',
    explanation: '2x + 5 = 17 → 2x = 12 → x = 6.',
  },
  {
    id: 'mth-002',
    subjectId: 'mathematics',
    year: 2022,
    exam: 'WAEC',
    question: 'The mean of 3, 5, 7, 9 is:',
    options: { A: '5', B: '6', C: '7', D: '8' },
    answer: 'B',
    explanation: 'Sum = 24, count = 4, mean = 24/4 = 6.',
  },
  {
    id: 'mth-003',
    subjectId: 'mathematics',
    year: 2021,
    exam: 'JAMB',
    question: 'Simplify: 2³ × 2²',
    options: { A: '2⁵', B: '2⁶', C: '4⁵', D: '2' },
    answer: 'A',
    explanation: 'Same base: add exponents. 2³ × 2² = 2⁵.',
  },
  {
    id: 'phy-001',
    subjectId: 'physics',
    year: 2023,
    exam: 'JAMB',
    question: 'The S.I. unit of force is the:',
    options: { A: 'Joule', B: 'Watt', C: 'Newton', D: 'Pascal' },
    answer: 'C',
    explanation: 'Force is measured in newtons (N). Joule is energy, watt is power, pascal is pressure.',
  },
  {
    id: 'phy-002',
    subjectId: 'physics',
    year: 2022,
    exam: 'WAEC',
    question: 'Which of the following is a vector quantity?',
    options: { A: 'Mass', B: 'Temperature', C: 'Velocity', D: 'Time' },
    answer: 'C',
    explanation: 'Velocity has magnitude and direction. Mass, temperature, and time are scalars.',
  },
  {
    id: 'phy-003',
    subjectId: 'physics',
    year: 2021,
    exam: 'JAMB',
    question: 'Light travels fastest in:',
    options: { A: 'Glass', B: 'Water', C: 'Air', D: 'Vacuum' },
    answer: 'D',
    explanation: 'The speed of light is maximum in a vacuum (~3 × 10⁸ m/s).',
  },
  {
    id: 'chm-001',
    subjectId: 'chemistry',
    year: 2023,
    exam: 'JAMB',
    question: 'The atomic number of an element is the number of:',
    options: { A: 'Neutrons', B: 'Protons', C: 'Electrons + neutrons', D: 'Nucleons' },
    answer: 'B',
    explanation: 'Atomic number = number of protons in the nucleus.',
  },
  {
    id: 'chm-002',
    subjectId: 'chemistry',
    year: 2022,
    exam: 'WAEC',
    question: 'A Brønsted-Lowry acid is a substance that:',
    options: {
      A: 'Accepts protons',
      B: 'Donates protons',
      C: 'Donates electrons',
      D: 'Accepts electrons',
    },
    answer: 'B',
    explanation: 'Brønsted-Lowry acid = proton (H⁺) donor.',
  },
  {
    id: 'chm-003',
    subjectId: 'chemistry',
    year: 2021,
    exam: 'JAMB',
    question: 'The process of converting a liquid to a gas is called:',
    options: { A: 'Condensation', B: 'Sublimation', C: 'Evaporation', D: 'Deposition' },
    answer: 'C',
    explanation: 'Evaporation is liquid → gas. Condensation is the reverse.',
  },
  {
    id: 'bio-001',
    subjectId: 'biology',
    year: 2023,
    exam: 'JAMB',
    question: 'The powerhouse of the cell is the:',
    options: { A: 'Nucleus', B: 'Ribosome', C: 'Mitochondria', D: 'Golgi apparatus' },
    answer: 'C',
    explanation: 'Mitochondria produce ATP — the cell’s energy currency.',
  },
  {
    id: 'bio-002',
    subjectId: 'biology',
    year: 2022,
    exam: 'WAEC',
    question: 'Photosynthesis takes place in the:',
    options: { A: 'Mitochondria', B: 'Chloroplast', C: 'Nucleus', D: 'Ribosome' },
    answer: 'B',
    explanation: 'Chloroplasts contain chlorophyll and are the site of photosynthesis.',
  },
  {
    id: 'bio-003',
    subjectId: 'biology',
    year: 2021,
    exam: 'JAMB',
    question: 'Which blood group is the universal donor?',
    options: { A: 'A', B: 'B', C: 'AB', D: 'O' },
    answer: 'D',
    explanation: 'Group O can generally donate to other ABO groups in emergencies.',
  },
  {
    id: 'eng-001',
    subjectId: 'english',
    year: 2023,
    exam: 'JAMB',
    question: 'Choose the option nearest in meaning to “abundant”:',
    options: { A: 'Scarce', B: 'Plentiful', C: 'Empty', D: 'Rare' },
    answer: 'B',
    explanation: 'Abundant means plentiful or more than enough.',
  },
  {
    id: 'eng-002',
    subjectId: 'english',
    year: 2022,
    exam: 'WAEC',
    question: 'The opposite of “generous” is:',
    options: { A: 'Kind', B: 'Stingy', C: 'Wealthy', D: 'Friendly' },
    answer: 'B',
    explanation: 'Generous means giving freely; stingy means unwilling to give.',
  },
  {
    id: 'eco-001',
    subjectId: 'economics',
    year: 2023,
    exam: 'JAMB',
    question: 'Demand for a commodity is said to be elastic when:',
    options: {
      A: 'Price change has little effect on quantity demanded',
      B: 'Quantity demanded changes a lot when price changes',
      C: 'Supply is fixed',
      D: 'Income is zero',
    },
    answer: 'B',
    explanation: 'Elastic demand: quantity demanded responds strongly to price changes.',
  },

  {
    id: 'mth-004',
    subjectId: 'mathematics',
    year: 2020,
    exam: 'WAEC',
    question: 'Factorize: x² − 5x + 6',
    options: { A: '(x−2)(x−3)', B: '(x+2)(x+3)', C: '(x−1)(x−6)', D: '(x+1)(x−6)' },
    answer: 'A',
    explanation: 'Numbers that multiply to 6 and add to −5 are −2 and −3 → (x−2)(x−3).',
  },
  {
    id: 'mth-005',
    subjectId: 'mathematics',
    year: 2019,
    exam: 'JAMB',
    question: 'What is 15% of 80?',
    options: { A: '8', B: '12', C: '15', D: '20' },
    answer: 'B',
    explanation: '15% of 80 = 0.15 × 80 = 12.',
  },
  {
    id: 'phy-004',
    subjectId: 'physics',
    year: 2020,
    exam: 'WAEC',
    question: 'Ohm’s law states that V is proportional to I when:',
    options: { A: 'Temperature is constant', B: 'Pressure is high', C: 'Mass is zero', D: 'Time is short' },
    answer: 'A',
    explanation: 'Ohm’s law holds for a metallic conductor at constant temperature.',
  },
  {
    id: 'phy-005',
    subjectId: 'physics',
    year: 2019,
    exam: 'JAMB',
    question: 'The unit of electric current is the:',
    options: { A: 'Volt', B: 'Ohm', C: 'Ampere', D: 'Coulomb' },
    answer: 'C',
    explanation: 'Current is measured in amperes (A). Volt is potential difference, ohm is resistance.',
  },
  {
    id: 'chm-004',
    subjectId: 'chemistry',
    year: 2020,
    exam: 'WAEC',
    question: 'Which gas is produced when dilute HCl reacts with zinc?',
    options: { A: 'Oxygen', B: 'Hydrogen', C: 'Chlorine', D: 'Nitrogen' },
    answer: 'B',
    explanation: 'Metal + dilute acid → salt + hydrogen gas.',
  },
  {
    id: 'chm-005',
    subjectId: 'chemistry',
    year: 2019,
    exam: 'JAMB',
    question: 'The pH of a neutral solution at 25°C is:',
    options: { A: '0', B: '7', C: '14', D: '1' },
    answer: 'B',
    explanation: 'Neutral water has pH 7 at 25°C.',
  },
  {
    id: 'bio-004',
    subjectId: 'biology',
    year: 2020,
    exam: 'WAEC',
    question: 'How many chambers does the human heart have?',
    options: { A: '2', B: '3', C: '4', D: '5' },
    answer: 'C',
    explanation: 'Four chambers: two atria and two ventricles.',
  },
  {
    id: 'bio-005',
    subjectId: 'biology',
    year: 2019,
    exam: 'JAMB',
    question: 'The process by which plants lose water vapour is:',
    options: { A: 'Respiration', B: 'Transpiration', C: 'Photosynthesis', D: 'Osmosis' },
    answer: 'B',
    explanation: 'Transpiration is water vapour loss mainly through stomata.',
  },
  {
    id: 'eng-003',
    subjectId: 'english',
    year: 2021,
    exam: 'JAMB',
    question: 'Choose the correctly spelled word:',
    options: { A: 'Accomodate', B: 'Acommodate', C: 'Accommodate', D: 'Acomodate' },
    answer: 'C',
    explanation: 'Accommodate has two c’s and two m’s.',
  },
  {
    id: 'eng-004',
    subjectId: 'english',
    year: 2020,
    exam: 'WAEC',
    question: '“She has sung the song” is in the:',
    options: { A: 'Simple past', B: 'Present perfect', C: 'Past perfect', D: 'Future perfect' },
    answer: 'B',
    explanation: 'Has + past participle = present perfect.',
  },
  {
    id: 'eco-003',
    subjectId: 'economics',
    year: 2021,
    exam: 'JAMB',
    question: 'A market with only one seller is a:',
    options: { A: 'Oligopoly', B: 'Monopoly', C: 'Perfect competition', D: 'Duopoly' },
    answer: 'B',
    explanation: 'Monopoly = single seller controls the market.',
  },
  {
    id: 'eco-004',
    subjectId: 'economics',
    year: 2020,
    exam: 'WAEC',
    question: 'Inflation is a sustained increase in:',
    options: { A: 'Unemployment', B: 'General price level', C: 'Exports only', D: 'Population' },
    answer: 'B',
    explanation: 'Inflation is a sustained rise in the general price level of goods and services.',
  },
  {
    id: 'eco-002',
    subjectId: 'economics',
    year: 2022,
    exam: 'WAEC',
    question: 'The basic economic problem is:',
    options: {
      A: 'Inflation',
      B: 'Scarcity',
      C: 'Unemployment',
      D: 'Taxation',
    },
    answer: 'B',
    explanation: 'Scarcity — limited resources vs unlimited wants — is the core problem of economics.',
  },
,
  {
    id: 'mth-neco-001',
    subjectId: 'mathematics',
    year: 2023,
    exam: 'NECO',
    question: 'Evaluate 3/4 + 1/6',
    options: { A: '5/12', B: '11/12', C: '1/2', D: '2/3' },
    answer: 'B',
    explanation: 'LCM of 4 and 6 is 12. 9/12 + 2/12 = 11/12.',
  },
  {
    id: 'mth-neco-002',
    subjectId: 'mathematics',
    year: 2022,
    exam: 'NECO',
    question: 'If the probability of an event is 0.35, the probability it does not occur is:',
    options: { A: '0.35', B: '0.65', C: '1.35', D: '0' },
    answer: 'B',
    explanation: 'P(not) = 1 − P = 1 − 0.35 = 0.65.',
  },
  {
    id: 'phy-neco-001',
    subjectId: 'physics',
    year: 2023,
    exam: 'NECO',
    question: 'Which of the following is a renewable energy source?',
    options: { A: 'Coal', B: 'Crude oil', C: 'Solar', D: 'Natural gas' },
    answer: 'C',
    explanation: 'Solar energy is renewable. Coal, oil and gas are fossil fuels.',
  },
  {
    id: 'phy-neco-002',
    subjectId: 'physics',
    year: 2021,
    exam: 'NECO',
    question: 'The unit of electric current is the:',
    options: { A: 'Volt', B: 'Ohm', C: 'Ampere', D: 'Watt' },
    answer: 'C',
    explanation: 'Current is measured in amperes (A).',
  },
  {
    id: 'chm-neco-001',
    subjectId: 'chemistry',
    year: 2022,
    exam: 'NECO',
    question: 'The most abundant gas in the atmosphere is:',
    options: { A: 'Oxygen', B: 'Carbon dioxide', C: 'Nitrogen', D: 'Hydrogen' },
    answer: 'C',
    explanation: 'Nitrogen is about 78% of dry air.',
  },
  {
    id: 'bio-neco-001',
    subjectId: 'biology',
    year: 2023,
    exam: 'NECO',
    question: 'Photosynthesis takes place mainly in the:',
    options: { A: 'Roots', B: 'Leaves', C: 'Flowers', D: 'Stem bark' },
    answer: 'B',
    explanation: 'Leaves contain chloroplasts where photosynthesis occurs.',
  },
  {
    id: 'eng-neco-001',
    subjectId: 'english',
    year: 2022,
    exam: 'NECO',
    question: 'Choose the word nearest in meaning to "benevolent":',
    options: { A: 'Cruel', B: 'Kind', C: 'Lazy', D: 'Angry' },
    answer: 'B',
    explanation: 'Benevolent means kind or charitable.',
  },
  {
    id: 'eco-neco-001',
    subjectId: 'economics',
    year: 2021,
    exam: 'NECO',
    question: 'A market with only one seller is called a:',
    options: { A: 'Oligopoly', B: 'Monopoly', C: 'Perfect competition', D: 'Duopoly' },
    answer: 'B',
    explanation: 'Monopoly = single seller controls the market.',
  },

]

export function questionsForSubject(subjectId: string): PastQuestion[] {
  return PAST_QUESTIONS.filter((q) => q.subjectId === subjectId)
}

export type ExamBoard = 'JAMB' | 'WAEC' | 'NECO' | 'ALL'

export function questionsForExam(
  subjectId: string,
  exam: ExamBoard = 'ALL'
): PastQuestion[] {
  const all = PAST_QUESTIONS.filter((q) => q.subjectId === subjectId)
  if (exam === 'ALL') return all
  return all.filter((q) => q.exam === exam)
}

export function countByExam(subjectId: string): Record<ExamBoard, number> {
  const all = PAST_QUESTIONS.filter((q) => q.subjectId === subjectId)
  return {
    ALL: all.length,
    JAMB: all.filter((q) => q.exam === 'JAMB').length,
    WAEC: all.filter((q) => q.exam === 'WAEC').length,
    NECO: all.filter((q) => q.exam === 'NECO').length,
  }
}

/** Suggested seconds per question by board (for timed practice). */
export function secondsPerQuestion(exam: ExamBoard): number {
  if (exam === 'JAMB') return 50
  if (exam === 'WAEC') return 75
  if (exam === 'NECO') return 70
  return 60
}
